// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CBCanteen.Server.WebHost.Migrations
{
    /// <inheritdoc />
    public partial class AddUserModels : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "LunchHours",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    DayOfWeek = table.Column<int>(type: "int", nullable: false),
                    StartTime = table.Column<TimeSpan>(type: "time", nullable: false),
                    EndTime = table.Column<TimeSpan>(type: "time", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LunchHours", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "UserPreferences",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ShowMeetings = table.Column<bool>(type: "bit", nullable: false),
                    SendEmail = table.Column<bool>(type: "bit", nullable: false),
                    CreateReminder = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserPreferences", x => x.UserId);
                });

            migrationBuilder.CreateTable(
                name: "UserLunchHours",
                columns: table => new
                {
                    UserId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    HasSameLunchHours = table.Column<bool>(type: "bit", nullable: false),
                    MondayLunchHoursId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    TuesdayLunchTimeId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    WednesdayLunchTimeId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ThursdayLunchTimeId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    FridayLunchTimeId = table.Column<string>(type: "nvarchar(450)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserLunchHours", x => x.UserId);
                    table.ForeignKey(
                        name: "FK_UserLunchHours_LunchHours_FridayLunchTimeId",
                        column: x => x.FridayLunchTimeId,
                        principalTable: "LunchHours",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                    table.ForeignKey(
                        name: "FK_UserLunchHours_LunchHours_MondayLunchHoursId",
                        column: x => x.MondayLunchHoursId,
                        principalTable: "LunchHours",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                    table.ForeignKey(
                        name: "FK_UserLunchHours_LunchHours_ThursdayLunchTimeId",
                        column: x => x.ThursdayLunchTimeId,
                        principalTable: "LunchHours",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                    table.ForeignKey(
                        name: "FK_UserLunchHours_LunchHours_TuesdayLunchTimeId",
                        column: x => x.TuesdayLunchTimeId,
                        principalTable: "LunchHours",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                    table.ForeignKey(
                        name: "FK_UserLunchHours_LunchHours_WednesdayLunchTimeId",
                        column: x => x.WednesdayLunchTimeId,
                        principalTable: "LunchHours",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                });

            migrationBuilder.CreateIndex(
                name: "IX_UserLunchHours_FridayLunchTimeId",
                table: "UserLunchHours",
                column: "FridayLunchTimeId");

            migrationBuilder.CreateIndex(
                name: "IX_UserLunchHours_MondayLunchHoursId",
                table: "UserLunchHours",
                column: "MondayLunchHoursId");

            migrationBuilder.CreateIndex(
                name: "IX_UserLunchHours_ThursdayLunchTimeId",
                table: "UserLunchHours",
                column: "ThursdayLunchTimeId");

            migrationBuilder.CreateIndex(
                name: "IX_UserLunchHours_TuesdayLunchTimeId",
                table: "UserLunchHours",
                column: "TuesdayLunchTimeId");

            migrationBuilder.CreateIndex(
                name: "IX_UserLunchHours_WednesdayLunchTimeId",
                table: "UserLunchHours",
                column: "WednesdayLunchTimeId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "UserLunchHours");

            migrationBuilder.DropTable(
                name: "UserPreferences");

            migrationBuilder.DropTable(
                name: "LunchHours");
        }
    }
}
