// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CBCanteen.Server.WebHost.Migrations
{
    /// <inheritdoc />
    public partial class AddDailyOrderModel : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "DailyOrders",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    MenuOneId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    MenuTwoId = table.Column<string>(type: "nvarchar(450)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DailyOrders", x => x.Id);
                    table.ForeignKey(
                        name: "FK_DailyOrders_Menus_MenuOneId",
                        column: x => x.MenuOneId,
                        principalTable: "Menus",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                    table.ForeignKey(
                        name: "FK_DailyOrders_Menus_MenuTwoId",
                        column: x => x.MenuTwoId,
                        principalTable: "Menus",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                });

            migrationBuilder.CreateTable(
                name: "DailyOrderMeal",
                columns: table => new
                {
                    DailyOrdersId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    FreeConsumptionId = table.Column<string>(type: "nvarchar(450)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DailyOrderMeal", x => new { x.DailyOrdersId, x.FreeConsumptionId });
                    table.ForeignKey(
                        name: "FK_DailyOrderMeal_DailyOrders_DailyOrdersId",
                        column: x => x.DailyOrdersId,
                        principalTable: "DailyOrders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                    table.ForeignKey(
                        name: "FK_DailyOrderMeal_Meals_FreeConsumptionId",
                        column: x => x.FreeConsumptionId,
                        principalTable: "Meals",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.NoAction);
                });

            migrationBuilder.CreateIndex(
                name: "IX_DailyOrderMeal_FreeConsumptionId",
                table: "DailyOrderMeal",
                column: "FreeConsumptionId");

            migrationBuilder.CreateIndex(
                name: "IX_DailyOrders_MenuOneId",
                table: "DailyOrders",
                column: "MenuOneId");

            migrationBuilder.CreateIndex(
                name: "IX_DailyOrders_MenuTwoId",
                table: "DailyOrders",
                column: "MenuTwoId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DailyOrderMeal");

            migrationBuilder.DropTable(
                name: "DailyOrders");
        }
    }
}
