// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CBCanteen.Server.WebHost.Migrations
{
    /// <inheritdoc />
    public partial class AddBridgeTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DailyOrderMeal");

            migrationBuilder.CreateTable(
                name: "DailyOrderMeals",
                columns: table => new
                {
                    DailyOrderId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    MealId = table.Column<string>(type: "nvarchar(450)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DailyOrderMeals", x => new { x.DailyOrderId, x.MealId });
                    table.ForeignKey(
                        name: "FK_DailyOrderMeals_DailyOrders_DailyOrderId",
                        column: x => x.DailyOrderId,
                        principalTable: "DailyOrders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_DailyOrderMeals_Meals_MealId",
                        column: x => x.MealId,
                        principalTable: "Meals",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_DailyOrderMeals_MealId",
                table: "DailyOrderMeals",
                column: "MealId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DailyOrderMeals");

            migrationBuilder.CreateTable(
                name: "DailyOrderMeal",
                columns: table => new
                {
                    DailyOrdersId = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    FreeConsumptionId = table.Column<string>(type: "nvarchar(450)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DailyOrderMeal", x => new { x.DailyOrdersId, x.FreeConsumptionId });
                    table.ForeignKey(
                        name: "FK_DailyOrderMeal_DailyOrders_DailyOrdersId",
                        column: x => x.DailyOrdersId,
                        principalTable: "DailyOrders",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_DailyOrderMeal_Meals_FreeConsumptionId",
                        column: x => x.FreeConsumptionId,
                        principalTable: "Meals",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_DailyOrderMeal_FreeConsumptionId",
                table: "DailyOrderMeal",
                column: "FreeConsumptionId");
        }
    }
}
